### ISSUE TITLE
website does not work

### ISSUE THREAD

**Issue by nova120** [jpwright/subway#24] opened 2021-12-11 23:07 UTC
when i went to the site it said "This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>" can someone fix this?

**Comment by jpwright** [comment] 2021-12-11 23:34
Duplicate of #23 
Use https://jpwright.github.io/subway/

**Closed by jpwright** 2021-12-11 23:34 UTC
